spring:
  application:
    name: spring-cloud-consul-consumer
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
#        register: false # 设置不需要注册到consul中
        serviceName: consul-demo-consumer
        healthCheckPath: /actuator/health
        healthCheckInterval: 15s

server:
  port: 9100
